FROM ubuntu:latest
# Usa la imagen oficial de Ubuntu como base.

RUN apt-get update && \
    apt-get install -y build-essential gcc gdb make && \
    apt-get clean
# - Actualiza los paquetes disponibles.
# - Instala herramientas esenciales para compilar y depurar en C.
# - Limpia la caché para reducir el tamaño de la imagen.

WORKDIR /workspace
# Define el directorio de trabajo dentro del contenedor.

CMD [ "bash" ]
# Abre una terminal bash por defecto al iniciar el contenedor.
